# Generated by Django 6.0.3 on 2026-04-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='output',
            field=models.TextField(max_length=10000),
        ),
    ]
